name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            target: ""
            id: "windows"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Clone source
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with pyinstaller
        shell: bash
        run: |
          pyinstaller --onedir --clean --console \
            --icon "icon.png" \
            --name league-ui-updater \
            --contents-directory deps \
            --add-data schemes:schemes \
            --add-data src/lib/cslol_tools:cslol_tools \
            --add-data src/lib/ritobin:ritobin \
            --hidden-import=lib.cslol_tools \
            --hidden-import=lib.ritobin \
            --hidden-import=utils.configuration \
            --hidden-import=utils.fs \
            ${{ matrix.target }} \
            src/main.py

      - name: Package
        shell: bash
        run: |
          mv ./dist/league-ui-modifier/ ./
          7z a league-ui-modifier-${{ matrix.id }}.zip league-ui-modifier/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: league-ui-modifier-${{ matrix.id }}.zip
